version: 2.1
orbs:
    slack: circleci/slack@4.1.1
   
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:

      - run: echo $SLACK_DEFAULT_CHANNEL
      - slack/notify:
#           template: basic_fail_1
          event: always
          mentions: '@henna'
          custom: |
        


{
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "This message contains a URL $CIRCLE_BUILD_URL\nSo does this one: $CIRCLE_BUILD_URL\nThis message contains a URL <$CIRCLE_BUILD_URL>\n<http://www.foo.com|This message *is* a link>\n<mailto:bob@example.com|Email Bob Roberts>"
			}
		}
	]
}



            
workflows:
  my_workflow:
    jobs:
      - my_job:  
          context:
            - SLACK_SECRETS
      - slack/on-hold:
          name: Notify Approval
          context:
            - SLACK_SECRETS          
          filters:
            branches:
              only: test         
              
              #test
              
              

