version: 2.1
orbs:
    slack: circleci/slack@4.4.4
    hello-world: tsub/hello-world@0.0.8
   
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:

      - run: echo $SLACK_DEFAULT_CHANNEL
      - hello-world/hello

      - slack/notify:
          custom: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "Deployed ${CIRCLE_PROJECT_REPONAME} to .",
                        "emoji": true
                      }
                    ]
                  },
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "View Job"
                        },
                        "url": "${CIRCLE_BUILD_URL}"
                      }
                    ]
                  }
                ]
              } 
              event: fail
              mentions: @${ME}
 
workflows:
  my_workflow:
    jobs:
      - my_job:  
          context:
            - SLACK_SECRETS

              

              

