version: 2.1
orbs:
    slack: circleci/slack@3.4.2
    hello: circleci/hello-build@0.0.14     
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - hello/circleci-env-highlights
      - hello/hello-triggerer
#       - slack/notify:
#         webhook: '${SLACK_WEBHOOK}'
    - slack/status:
        success_message: 🎉 A $CIRCLE_JOB job has succeeded!
        failure_message: 🔴 A $CIRCLE_JOB job has failed!
        fail_only: false
        webhook: '${SLACK_WEBHOOK}'
        only_for_branches: master   
workflows:
  my_workflow:
    jobs:
      - my_job

