version: 2.0
orbs:
    slack: circleci/slack@3.4.2
    hello: circleci/hello-build@0.0.14     
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - hello/circleci-env-highlights
      - hello/hello-triggerer
      - slack/notify:
        webhook: '${SLACK_WEBHOOK}'
workflows:
  my_workflow:
    jobs:
      - my_job

