version: 2.1
orbs:
    slack: circleci/slack@4.0.0
   
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:
      - run: echo "hello world"     
#       - slack/status:
#             success_message: Success! $CIRCLE_JOB ran on $CIRCLE_BRANCH branch by $CIRCLE_PROJECT_USERNAME - $CIRCLE_BUILD_URL 
#             failure_message: 🔴 A $CIRCLE_JOB job has failed!
#             fail_only: false
#             webhook: $SLACK_WEBHOOK
#             only_for_branches: master   
#             channel : test-app
      - slack/notify:
          template: 'failed'    
          mentions: "@henna"
          
            
workflows:
  my_workflow:
    jobs:
      - my_job:  
          context:
            - SLACK_SECRETS


     

