version: 2.1

orbs:
  slack: circleci/slack@4.1.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: &setup_slack_env
          name: Prepare Slack environment
          command: |
            echo "export COMMIT_MESSAGE='commit message'" >> $BASH_ENV
            echo "export COMMIT_AUTHOR='MEEEEEE'" >> $BASH_ENV
      - run:
          command: |
            exit 1
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run: *setup_slack_env
      - run:
          command: |
            exit 1
  lint:
    docker:
      - image: circleci/node:latest
    steps:

      - run: *setup_slack_env
      - run:
          command: |
            exit 1
  integration-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: *setup_slack_env
      - run:
          command: |
            exit 1
  notify-success:
    docker:
    - image: cimg/base:stable

    steps:
    - run: *setup_slack_env
    - slack/notify:
        custom: |
          {
            "text": "",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "✅ *Success* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}` by ${COMMIT_AUTHOR}:\n${COMMIT_MESSAGE}"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${CIRCLE_BUILD_URL}"
                  }
                ]
              }
            ]
          }
        event: always
workflows:
  build-and-test:
    jobs:
    - build:
        context: [slack]
        post-steps: &failure_post_steps
        - slack/notify:
            custom: |
              {
                 "text": "CircleCI job failed.",
                 "blocks": [
                     {
                       "type": "header",
                       "text": {
                          "type": "plain_text",
                          "text": "Job Failed. :red_circle:",
                          "emoji": true
                       }
                    },
                    {
                       "type": "section",
                       "fields": [{
                          "type": "mrkdwn",
                          "text": "*Job*: ${CIRCLE_JOB}"
                       }]
                    },
                    {
                       "type": "section",
                       "fields": [{
                             "type": "mrkdwn",
                             "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                          },
                          {
                             "type": "mrkdwn",
                             "text": "*Branch*: $CIRCLE_BRANCH"
                          },
                          {
                             "type": "mrkdwn",
                             "text": "*Commit*: $CIRCLE_SHA1"
                          }
                       ],
                       "accessory": {
                          "type": "image",
                          "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                          "alt_text": "CircleCI logo"
                       }
                    },
                        {
                            "type": "actions",
                            "elements": [{
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "View More",
                                "emoji": true
                            },
                            "value":  "view_job",
                            "url":  "$CIRCLE_BUILD_URL"
                        },{
                              "type": "button",
                              "text": {
                                "type": "plain_text",
                                "text": "View Report",
                                "emoji": true
                              },
                              "value": "view_job",
                              "url": "$ARTIFACT_URL"
                            }

                        ]
                    }

                 ]
              }    
        event: always              
    - test:
        context: SLACK_SECRETS
        post-steps: *failure_post_steps
    - lint:
        context: SLACK_SECRETS
        post-steps: *failure_post_steps
    - integration-test:
        context: SLACK_SECRETS
        post-steps: *failure_post_steps
    - notify-success:
        context: SLACK_SECRETS
        requires: [build, lint, test, integration-test]
