version: '2.1'
orbs:
  slack: circleci/slack@4.4.1
jobs:
  notify:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - slack/notify:
          template: basic_success_1
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
          
          #test

