# version: 2.1
# orbs:
#     slack: circleci/slack@3.4.2
#     hello: circleci/hello-build@0.0.14     
# jobs:
#   my_job:
#     docker:
#       - image: circleci/node
#     steps:
#       - checkout
#       - hello/circleci-env-highlights
#       - hello/hello-triggerer
#       - run:
#             name: Upload CodeCov.io Data
#             command: slack/status:
#                 success_message: 🎉 @$name $CIRCLE_USERNAME GIT commit $CIRCLE_SHA1 checked into Branch $CIRCLE_BRANCH has succeeded with $CIRCLE_JOB job.... $CIRCLE_BUILD_URL
#                 webhook: https://hooks.slack.com/services/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
#             when: always

# #       - slack/notify:
# #         webhook: '${SLACK_WEBHOOK}'
#       - slack/status:
# #             when: always
# #             success_message: 🎉 A $CIRCLE_JOB job has succeeded!.... without quotes are channel name...$CIRCLE_USERNAME
#             success_message: Success: $CIRCLE_BUILD_URL $CIRCLE_JOB ran on $CIRCLE_BRANCH. Author : $CIRCLE_PROJECT_USERNAME
#             failure_message: 🔴 A $CIRCLE_JOB job has failed!
#             fail_only: false
#             webhook: https://hooks.slack.com/services/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
#             only_for_branches: master   
#             channel : test-app
# workflows:
#   my_workflow:
#     jobs:
#       - my_job
#       - slack/approval-notification:
#           message: Pending approval
#           webhook: https://hooks.slack.com/services/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
          
# version: 2.1
# orbs:
#     slack: circleci/slack@3.4.2
#     hello: circleci/hello-build@0.0.14     
# jobs:
#   my_job:
#     docker:
#       - image: circleci/node
#     steps:
#       - checkout
#       - hello/circleci-env-highlights
#       - hello/hello-triggerer
#       - run:
#             name: Upload CodeCov.io Data
#             command: bash <(curl -s https://codecov.io/bash) -F unittests
#             when: always

# #       - slack/notify:
# #         webhook: '${SLACK_WEBHOOK}'
#       - slack/status:
# #             when: always
# #             success_message: 🎉 A $CIRCLE_JOB job has succeeded!.... without quotes are channel name...$CIRCLE_USERNAME
# # `Success:` $CIRCLE_BUILD_URL $CIRCLE_JOB `ran on` $CIRCLE_BRANCH. `Author` : $CIRCLE_PROJECT_USERNAME
#             success_message: 🎉 Job:  $CIRCLE_JOB ran on $CIRCLE_BRANCH. Author:  $CIRCLE_PROJECT_USERNAME
#             failure_message: 🔴 A $CIRCLE_JOB job has failed!
#             fail_only: false
#             webhook: https://hooks.slack.com/services/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
#             only_for_branches: master   
#             channel : test-app
# workflows:
#   my_workflow:
#     jobs:
#       - my_job          
version: 2.1
orbs:
    slack: circleci/slack@3.4.2
    hello: circleci/hello-build@0.0.14     
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - hello/circleci-env-highlights
      - hello/hello-triggerer
      - run:
            name: Upload CodeCov.io Data
            command: bash <(curl -s https://codecov.io/bash) -F unittests
            when: always

#       - slack/notify:
#         webhook: '${SLACK_WEBHOOK}'
      - slack/status:
#             when: always
#             success_message: 🎉 A $CIRCLE_JOB job has succeeded!.... without quotes are channel name...$CIRCLE_USERNAME
            success_message: 🎉 $CIRCLE_USERNAME GIT commit $CIRCLE_SHA1 checked into Branch $CIRCLE_BRANCH has succeeded with $CIRCLE_JOB job.... $CIRCLE_BUILD_URL
            failure_message: 🔴 A $CIRCLE_JOB job has failed!
            fail_only: false
            webhook: $SLACK_WEBHOOK
            only_for_branches: master   
            channel : test-app
workflows:
  my_workflow:
    jobs:
      - my_job      
      - slack/approval-notification:
          message: Pending approval
          webhook: $SLACK_WEBHOOK
