version: 2.1
orbs:
    slack: circleci/slack@4.10.1
    hello-world: tsub/hello-world@0.0.8
   
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:

      - run: echo $SLACK_DEFAULT_CHANNEL
      - hello-world/hello

      - slack/notify:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: fail     
          mentions: ${ME}
 
workflows:
  my_workflow:
    jobs:
      - my_job:  
          context:
            - SLACK_SECRETS

              

              

