version: 2.1
orbs:
    slack: circleci/slack@4.0.0
   
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:
      - run: echo "hello world"     
      - slack/notify:
          template: basic_fail_1
          event: always
          mentions: '@henna'
          channel: 'C01CM3VM6E8'

            
workflows:
  my_workflow:
    jobs:
      - my_job:  
          context:
            - SLACK_SECRETS


     

