version: '2.1'
orbs:
  slack: circleci/slack@4.4.3
  maven: circleci/maven@1.1.1
jobs:
  notify:
    docker:
      - image: cimg/node
    steps:
      - run: jq --version
      - slack/notify:
          template: basic_success_1
          event: always
workflows:
  send-notification:
    jobs:
      - maven/test      
      - notify:
          context: slack-secrets
   
          
          #test

