version: 2.1
orbs:
    slack: circleci/slack@3.4.2
    hello: circleci/hello-build@0.0.14     
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - hello/circleci-env-highlights
      - hello/hello-triggerer
      - run:
            name: Upload CodeCov.io Data
            command: bash <(curl -s https://codecov.io/bash) -F unittests
            when: always

#       - slack/notify:
#         webhook: '${SLACK_WEBHOOK}'
      - slack/status:
#             when: always
#             success_message: 🎉 A $CIRCLE_JOB job has succeeded!.... without quotes are channel name...$CIRCLE_USERNAME
            success_message: 🎉 @$name $CIRCLE_USERNAME GIT commit $CIRCLE_SHA1 checked into Branch $CIRCLE_BRANCH has succeeded with $CIRCLE_JOB job.... $CIRCLE_BUILD_URL
            failure_message: 🔴 A $CIRCLE_JOB job has failed!
            fail_only: false
            webhook: https://hooks.slack.com/services/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
            only_for_branches: master   
            channel : test-app
workflows:
  my_workflow:
    jobs:
      - my_job
      
     #test

