version: 2.1
orbs:
    slack: circleci/slack@4.1.1
   
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:

      - run: echo $SLACK_DEFAULT_CHANNEL
      - slack/notify:
#           template: basic_fail_1
          event: always
          mentions: '@henna'
          channel: G017SNS0AJC
          custom: | 
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Failed: $CIRCLE_USERNAME's build of \n<$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME>\n(<https://app.circleci.com/pipelines/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?branch=$CIRCLE_BRANCH|$CIRCLE_BRANCH>) \n- <$CIRCLE_BUILD_URL|$CIRCLE_JOB> failed" 
                        }
                    }
                ]
            }              



            
workflows:
  my_workflow:
    jobs:
      - my_job:  
          context:
            - SLACK_SECRETS
#       - slack/on-hold:
#           name: Notify Approval
#           context:
#             - SLACK_SECRETS          
#           filters:
#             branches:
#               only: test         
              
              
              #test
              

              

