version: 2.1
orbs:
    slack: circleci/slack@3.4.2
    hello: circleci/hello-build@0.0.14     
jobs:
  my_job:
    docker:
      - image: circleci/node
    steps:
      - run: echo "hello world"     
      - slack/status:
            success_message: Success! $CIRCLE_BUILD_URL $CIRCLE_JOB ran on $CIRCLE_BRANCH Author- $CIRCLE_PROJECT_USERNAME
            failure_message: 🔴 A $CIRCLE_JOB job has failed!
            fail_only: false
            webhook: $SLACK_WEBHOOK
            only_for_branches: master   
            channel : test-app
workflows:
  my_workflow:
    jobs:
      - my_job      
      - slack/approval-notification:
          message: Pending approval
          webhook: $SLACK_WEBHOOK
