version: '2.1'
orbs:
  slack: circleci/slack@4.4.3
  maven: circleci/maven@1.2.0
jobs:
  notify:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - slack/notify:
          template: basic_success_1
          event: always
          
          
  testing:
    docker:
      - image: cimg/openjdk:13.0
    steps:
      - checkout  
    
    
workflows:
  send-notification:
    jobs:
      - testing
      - maven/test:
          command: package
          settings_file: .circleci/settings.xml
          
      - notify:
          context: slack-secrets
   
          
          #test

