version: '2.1'
orbs:
  slack: circleci/slack@4.4.3
jobs:
  notify:
    docker:
      - image: amazon/aws-cli 
    steps:
      - run: jq --version
      - slack/notify:
          template: basic_success_1
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
          
          #test

