version: '2.1'
slack-fail-post-step: &slack-notify-failure
  slack/notify:
    event: fail

send-pass-notification: &slack-notify-success
  slack/notify:
    event: pass

orbs:
  slack: circleci/slack@4.12.5
jobs:
  notify:
    macos:
      xcode: 14.1.0
    resource_class: macos.m1.medium.gen1
    steps:
      - run: echo "hello world" 
 
      # - run : pwd
      # - run : echo 'export MY_TEMPLATE=$(cat /slack/my_template.json)' >> $BASH_ENV
      # - run : echo $MY_TEMPLATE
      - slack/notify:
          event: always 

workflows:
  send-notification:
    jobs:
      - notify:
          context: 
            - SLACK_SECRETS

          
         


