version: '2.1'
orbs:
  slack: circleci/slack@4.9.3
jobs:
  notify:
    docker:
      - image: cimg/base:2020.01
    steps:
      - slack/notify:
          custom: |
            {
               "text": "CircleCI job failed.",
               "blocks": [
                   {
                     "type": "header",
                     "text": {
                        "type": "plain_text",
                        "text": "Job Failed. :red_circle:",
                        "emoji": true
                     }
                  },
                  {
                     "type": "section",
                     "fields": [{
                        "type": "mrkdwn",
                        "text": "*Job*: ${CIRCLE_JOB}"
                     }]
                  },
                  {
                     "type": "section",
                     "fields": [{
                           "type": "mrkdwn",
                           "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                        },
                        {
                           "type": "mrkdwn",
                           "text": "*Branch*: $CIRCLE_BRANCH"
                        },
                        {
                           "type": "mrkdwn",
                           "text": "*Commit*: $CIRCLE_SHA1"
                        }
                     ],
                     "accessory": {
                        "type": "image",
                        "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                        "alt_text": "CircleCI logo"
                     }
                  },
                      {
                          "type": "actions",
                          "elements": [{
                          "type": "button",
                          "text": {
                              "type": "plain_text",
                              "text": "View More",
                              "emoji": true
                          },
                          "value":  "view_job",
                          "url":  "$CIRCLE_BUILD_URL"
                      },{
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "View Report",
                              "emoji": true
                            },
                            "value": "view_job",
                            "url": "$ARTIFACT_URL"
                          }

                      ]
                  }

               ]
            }
workflows:
  send-notification:
    jobs:
      - notify:
          context: SLACK_SECRETS
          
         


