version: '2.1'
orbs:
  slack: circleci/slack@4.4.3
jobs:
  notify:
    docker:
      - image: cimg/node@sha256:157f3cf0f19d49187d0e1c31984472e3d2f4fe4f3642199ebf8d7845441fedb5
    steps:
      - slack/notify:
          template: basic_success_1
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
          
          #test

